### PR TITLE
UX & UI Update + Spring Cleaning

### PR DESCRIPTION
**Pull request by japorized**
Hi Blackrobe. Remember the guy who said he'd be doing some UI for the EXP calculator? I'm finally getting some time to do it so already did a few things here.

Summary:
- added Header for the static page
- slightly less verbose UX (am still thinking of how to minify the about of words for the time calculator)
- separated the calculator into a js file for less clutter
- created a global css file for local management (overrides some Bootstrap styles)
- added a gitignore file (cause I have DS_Store files, and I'm using jekyll serve to watch how the site turns out, thus ignored "_site/" here)

I have not tested the page on mobile so not entirely sure how it will turn out on phones or tablets.

Do let me know if there's anything wrong.

Cheers!
Japorized

### CODE REVIEW

**Comment by Blackrobe** [comment]
Oh hello japorized ;D
I only been using Github for a month, so I still need to figure out how things here works etc (I only completed the free short tutorial at gitreal), I think I need a few hours or a few days to... "merge your changes", or "commit" is it? or is it "pull" ? man.

Thank you so much for designing the UI + other things, I really appreciate it.

**Comment by Blackrobe** [comment]
um... by the way I've expanded the tool to include level 501 to 999

**Comment by japorized** [comment]
It's okay. I'm pretty new myself too, and struggling to get to know how things work, so take your time.
It's actually called merging pull requests for the case here. If you're using the web client, there should be a purple button for merging a pull request.

And I only noticed that I didn't change the wordings after sending the pull request. :P Oops...

**Comment by Blackrobe** [comment]
either I'm colorblind or I have absolutely no idea about what that green button do -_-

anyway, I see that the tool looks awesome now :+1:

**Comment by Blackrobe** [comment]
ah, if you don't mind, I'm gonna change some text now:
- Current Level (51-299) ---> Current Level (51-998) and changing the default from 51 into blank.
- Desired Level (max 300) ---> Desired Level (max 999) and changing the default from 100 into ~~214~~ blank.
- changing Quest EXP defaults from 1000 into 16600 (amount of EXP from Changing the World, 2x EXP event).

**Comment by japorized** [comment]
Sorry, didn't mean to say purple there. That's for merged pull requests.

And yeah, go ahead and change em. I'll just fetch from your repo later.

I'm not sure what else I want to add for now, for the designs. Thought of something BF-ish (hence the 'golden' border), but not sure where exactly to start either. Am also worried about copyright infringements, if Gumi/Alim minds.

**Pull request merged**
